export const INITIAL_PROJECT = {
  "channels": [
    {
      "id": 0,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 1,
      "program": 4,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/fm2/harmonics/1.0/timbre/0.5/morph/0.2/decay/1.0/sustain/0.5/release/0.3"
    },
    {
      "id": 2,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 3,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 4,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 5,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 6,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 7,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 8,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 9,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": ""
    },
    {
      "id": 10,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 11,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 12,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 13,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 14,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    },
    {
      "id": 15,
      "program": 0,
      "volume": 100,
      "pan": 64,
      "mute": false,
      "solo": false,
      "activeNotes": {},
      "mode": "gm",
      "customSyntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2"
    }
  ],
  "drumMap": {
    "35": "/sound/bd/n/0/gain/1.2/sustain/0/decay/0.5",
    "36": "/sound/bd/n/1/gain/1.2/sustain/0/decay/0.5",
    "37": "/sound/rim/n/0/sustain/0/decay/0.2",
    "38": "/sound/sd/n/0/gain/1.1/sustain/0/decay/0.4",
    "39": "/sound/cp/n/0/sustain/0/decay/0.3",
    "40": "/sound/sd/n/1/sustain/0/decay/0.4",
    "41": "/sound/tom/n/0/sustain/0/decay/0.6",
    "42": "/sound/hh/n/0/sustain/0/decay/0.1",
    "43": "/sound/tom/n/1/sustain/0/decay/0.6",
    "44": "/sound/hh/n/2/sustain/0/decay/0.1",
    "45": "/sound/tom/n/2/sustain/0/decay/0.5",
    "46": "/sound/hh/n/4/sustain/0/decay/0.4",
    "47": "/sound/tom/n/3/sustain/0/decay/0.5",
    "48": "/sound/tom/n/4/sustain/0/decay/0.4",
    "49": "/sound/cy/n/0/sustain/0/decay/1.5",
    "50": "/sound/tom/n/5/sustain/0/decay/0.4",
    "51": "/sound/ride/n/0/sustain/0/decay/2.0",
    "52": "/sound/cy/n/1/sustain/0/decay/1.2",
    "53": "/sound/ride/n/1/sustain/0/decay/1.0",
    "54": "/sound/perc/n/0/sustain/0/decay/0.3",
    "55": "/sound/cy/n/2/sustain/0/decay/0.8",
    "56": "/sound/cow/n/0/sustain/0/decay/0.3",
    "57": "/sound/cy/n/3/sustain/0/decay/1.5",
    "58": "/sound/perc/n/1/sustain/0/decay/0.4",
    "59": "/sound/ride/n/2/sustain/0/decay/2.0",
    "60": "/sound/perc/n/2/sustain/0/decay/0.3",
    "61": "/sound/perc/n/3/sustain/0/decay/0.3",
    "62": "/sound/perc/n/4/sustain/0/decay/0.4",
    "63": "/sound/perc/n/5/sustain/0/decay/0.4",
    "64": "/sound/perc/n/6/sustain/0/decay/0.5",
    "65": "/sound/perc/n/7/sustain/0/decay/0.4",
    "66": "/sound/perc/n/8/sustain/0/decay/0.5",
    "67": "/sound/perc/n/9/sustain/0/decay/0.3",
    "68": "/sound/perc/n/10/sustain/0/decay/0.4",
    "69": "/sound/perc/n/11/sustain/0/decay/0.2",
    "70": "/sound/perc/n/12/sustain/0/decay/0.2"
  },
  "sampleLibraryUrl": "tidalcycles:Dirt-Samples",
  "instruments": [
    { "id": 0, "name": "Acoustic Grand Piano", "category": "Piano", "syntax": "/sound/tri/attack/0.005/decay/1.5/sustain/0.0/release/0.5/lpf/8000/gain/1.2" },
    { "id": 1, "name": "Bright Acoustic Piano", "category": "Piano", "syntax": "/sound/tri/attack/0.005/decay/1.2/sustain/0.0/release/0.4/lpf/10000/gain/1.3" },
    { "id": 2, "name": "Electric Grand Piano", "category": "Piano", "syntax": "/sound/tri/attack/0.005/decay/2.0/sustain/0.2/release/0.6/lpf/6000/chorus/0.3" },
    { "id": 3, "name": "Honky-tonk Piano", "category": "Piano", "syntax": "/sound/saw/attack/0.01/decay/1.0/sustain/0.0/release/0.4/lpf/3000/lpq/0.3/detune/5" },
    { "id": 4, "name": "Electric Piano 1", "category": "Piano", "syntax": "/sound/fm2/harmonics/1.0/timbre/0.5/morph/0.2/decay/1.0/sustain/0.5/release/0.3" },
    { "id": 5, "name": "Electric Piano 2", "category": "Piano", "syntax": "/sound/fm2/harmonics/1.0/timbre/0.7/morph/0.1/decay/1.5/sustain/0.4/release/0.4" },
    { "id": 6, "name": "Harpsichord", "category": "Piano", "syntax": "/sound/saw/attack/0.005/decay/0.5/sustain/0.6/release/0.1/lpf/5000/lpq/0.1" },
    { "id": 7, "name": "Clavinet", "category": "Piano", "syntax": "/sound/pulse/pw/0.2/attack/0.005/decay/1.0/sustain/0.4/release/0.2/lpf/3000" },
    
    // Chromatic Percussion
    { "id": 8, "name": "Celesta", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.5/timbre/0.8/morph/0.1/decay/0.8/sustain/0" },
    { "id": 9, "name": "Glockenspiel", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.5/timbre/0.9/morph/0.1/decay/0.6/sustain/0" },
    { "id": 10, "name": "Music Box", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.5/timbre/0.4/morph/0.0/decay/1.0/sustain/0" },
    { "id": 11, "name": "Vibraphone", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.5/timbre/0.2/morph/0.3/decay/2.0/sustain/0/tremolo/0.5" },
    { "id": 12, "name": "Marimba", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.3/timbre/0.4/morph/0.5/decay/0.4/sustain/0" },
    { "id": 13, "name": "Xylophone", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.3/timbre/0.6/morph/0.6/decay/0.3/sustain/0" },
    { "id": 14, "name": "Tubular Bells", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.8/timbre/0.8/morph/0.2/decay/1.5/sustain/0" },
    { "id": 15, "name": "Dulcimer", "category": "Chromatic Percussion", "syntax": "/sound/modal/harmonics/0.5/timbre/0.6/morph/0.3/decay/0.8/sustain/0" },
    
    // Organ
    { "id": 16, "name": "Drawbar Organ", "category": "Organ", "syntax": "/sound/saw/lpf/2000/lpq/0.2/sustain/1.0/attack/0.05/decay/0.0/release/0.1/chorus/0.3" },
    { "id": 17, "name": "Percussive Organ", "category": "Organ", "syntax": "/sound/pulse/pw/0.3/attack/0.01/sustain/0.8/release/0.1/lpf/3000" },
    { "id": 18, "name": "Rock Organ", "category": "Organ", "syntax": "/sound/saw/lpf/4000/distort/0.5/sustain/1.0/release/0.1" },
    { "id": 19, "name": "Church Organ", "category": "Organ", "syntax": "/sound/saw/attack/0.05/sustain/1.0/release/0.2/chorus/0.5/reverb/0.4/lpf/2500" },
    { "id": 20, "name": "Reed Organ", "category": "Organ", "syntax": "/sound/saw/attack/0.05/sustain/1.0/release/0.2/lpf/1500" },
    { "id": 21, "name": "Accordion", "category": "Organ", "syntax": "/sound/tri/attack/0.1/sustain/0.9/release/0.2/vibrato/0.5/lpf/1500" },
    { "id": 22, "name": "Harmonica", "category": "Organ", "syntax": "/sound/saw/lpf/1500/sustain/0.9/release/0.1/harmonics/0.8" },
    { "id": 23, "name": "Tango Accordion", "category": "Organ", "syntax": "/sound/tri/attack/0.1/sustain/0.9/release/0.1/lpf/1800" },
    
    // Guitar
    { "id": 24, "name": "Acoustic Guitar (nylon)", "category": "Guitar", "syntax": "/sound/string/timbre/0.3/harmonics/0.2/morph/0.6/decay/0.6/sustain/0.0" },
    { "id": 25, "name": "Acoustic Guitar (steel)", "category": "Guitar", "syntax": "/sound/string/timbre/0.5/harmonics/0.3/morph/0.7/decay/0.8/sustain/0.0" },
    { "id": 26, "name": "Electric Guitar (jazz)", "category": "Guitar", "syntax": "/sound/sine/harmonics/0.4/decay/1.0/sustain/0.2/lpf/3000" },
    { "id": 27, "name": "Electric Guitar (clean)", "category": "Guitar", "syntax": "/sound/saw/lpf/3000/sustain/0.5/release/0.2/chorus/0.3" },
    { "id": 28, "name": "Electric Guitar (muted)", "category": "Guitar", "syntax": "/sound/pulse/pw/0.2/lpf/2000/sustain/0.3/release/0.1" },
    { "id": 29, "name": "Overdriven Guitar", "category": "Guitar", "syntax": "/sound/saw/lpf/5000/distort/4.0/sustain/0.8/release/0.2" },
    { "id": 30, "name": "Distortion Guitar", "category": "Guitar", "syntax": "/sound/saw/lpf/4000/distort/8.0/sustain/0.8/release/0.2" },
    { "id": 31, "name": "Guitar Harmonics", "category": "Guitar", "syntax": "/sound/sine/harmonics/0.9/attack/0.05/decay/2.0/sustain/0.0" },
    
    // Bass
    { "id": 32, "name": "Acoustic Bass", "category": "Bass", "syntax": "/sound/tri/lpf/600/sustain/0.6/decay/0.5" },
    { "id": 33, "name": "Electric Bass (finger)", "category": "Bass", "syntax": "/sound/saw/lpf/800/lpq/0.3/sustain/0.7/attack/0.02" },
    { "id": 34, "name": "Electric Bass (pick)", "category": "Bass", "syntax": "/sound/saw/lpf/1200/lpq/0.4/sustain/0.7/attack/0.01" },
    { "id": 35, "name": "Fretless Bass", "category": "Bass", "syntax": "/sound/pulse/pw/0.1/lpf/1000/sustain/0.0/decay/0.3/attack/0.01" },
    { "id": 36, "name": "Slap Bass 1", "category": "Bass", "syntax": "/sound/saw/lpf/2000/lpq/0.6/sustain/0.5/attack/0.005" },
    { "id": 37, "name": "Slap Bass 2", "category": "Bass", "syntax": "/sound/saw/lpf/1500/lpq/0.5/sustain/0.5/attack/0.005" },
    { "id": 38, "name": "Synth Bass 1", "category": "Bass", "syntax": "/sound/saw/lpf/800/lpq/0.6/sustain/0.8/attack/0.01" },
    { "id": 39, "name": "Synth Bass 2", "category": "Bass", "syntax": "/sound/saw/lpf/600/lpq/0.8/sustain/0.8/attack/0.01" },
    
    // Strings
    { "id": 40, "name": "Violin", "category": "Strings", "syntax": "/sound/saw/attack/0.1/decay/0.2/sustain/0.8/release/0.4/lpf/3000/vibrato/0.4" },
    { "id": 41, "name": "Viola", "category": "Strings", "syntax": "/sound/saw/attack/0.15/decay/0.2/sustain/0.8/release/0.5/lpf/2500" },
    { "id": 42, "name": "Cello", "category": "Strings", "syntax": "/sound/saw/attack/0.2/decay/0.3/sustain/0.8/release/0.6/lpf/2000" },
    { "id": 43, "name": "Contrabass", "category": "Strings", "syntax": "/sound/saw/attack/0.3/decay/0.4/sustain/0.8/release/0.8/lpf/1500" },
    { "id": 44, "name": "Tremolo Strings", "category": "Strings", "syntax": "/sound/saw/attack/0.1/sustain/0.8/tremolo/0.8/lpf/3000" },
    { "id": 45, "name": "Pizzicato Strings", "category": "Strings", "syntax": "/sound/tri/attack/0.01/decay/0.2/sustain/0.0/lpf/2000" },
    { "id": 46, "name": "Orchestral Harp", "category": "Strings", "syntax": "/sound/string/timbre/0.8/decay/2.0/sustain/0.2" },
    { "id": 47, "name": "Timpani", "category": "Strings", "syntax": "/sound/modal/harmonics/0.1/decay/0.5/sustain/0.0" },
    
    // Ensemble
    { "id": 48, "name": "String Ensemble 1", "category": "Ensemble", "syntax": "/sound/saw/attack/0.4/sustain/0.9/release/0.8/lpf/3000/chorus/0.5" },
    { "id": 49, "name": "String Ensemble 2", "category": "Ensemble", "syntax": "/sound/saw/attack/0.5/sustain/0.8/release/1.0/lpf/2500/chorus/0.6" },
    { "id": 50, "name": "SynthStrings 1", "category": "Ensemble", "syntax": "/sound/saw/attack/0.3/sustain/0.8/release/0.5/lpf/4000/chorus/0.4" },
    { "id": 51, "name": "SynthStrings 2", "category": "Ensemble", "syntax": "/sound/saw/attack/0.4/sustain/0.7/release/0.6/lpf/3000/chorus/0.5" },
    { "id": 52, "name": "Choir Aahs", "category": "Ensemble", "syntax": "/sound/tri/attack/0.5/sustain/0.8/release/0.5/lpf/1000/chorus/0.8/reverb/0.5" },
    { "id": 53, "name": "Voice Oohs", "category": "Ensemble", "syntax": "/sound/sine/attack/0.6/sustain/0.8/release/0.6/lpf/800/chorus/0.7" },
    { "id": 54, "name": "Synth Voice", "category": "Ensemble", "syntax": "/sound/tri/attack/0.4/sustain/0.8/release/0.4/lpf/1200/chorus/0.6" },
    { "id": 55, "name": "Orchestra Hit", "category": "Ensemble", "syntax": "/sound/saw/attack/0.01/decay/0.2/sustain/0.0/lpf/5000/spread/50" },
    
    // Brass
    { "id": 56, "name": "Trumpet", "category": "Brass", "syntax": "/sound/saw/attack/0.05/sustain/0.8/release/0.2/lpf/2500/lpe/500" },
    { "id": 57, "name": "Trombone", "category": "Brass", "syntax": "/sound/saw/attack/0.08/sustain/0.8/release/0.3/lpf/1500/lpe/400" },
    { "id": 58, "name": "Tuba", "category": "Brass", "syntax": "/sound/saw/attack/0.1/sustain/0.8/release/0.4/lpf/800/lpe/300" },
    { "id": 59, "name": "Muted Trumpet", "category": "Brass", "syntax": "/sound/saw/attack/0.05/sustain/0.7/release/0.2/lpf/1200" },
    { "id": 60, "name": "French Horn", "category": "Brass", "syntax": "/sound/saw/attack/0.1/sustain/0.7/release/0.3/lpf/1000" },
    { "id": 61, "name": "Brass Section", "category": "Brass", "syntax": "/sound/saw/attack/0.08/sustain/0.8/release/0.3/lpf/2000/spread/30" },
    { "id": 62, "name": "SynthBrass 1", "category": "Brass", "syntax": "/sound/saw/attack/0.1/sustain/0.7/lpf/2000/lpe/1000/lpd/0.3/chorus/0.4" },
    { "id": 63, "name": "SynthBrass 2", "category": "Brass", "syntax": "/sound/saw/attack/0.1/sustain/0.7/lpf/2500/lpe/1200/lpd/0.2/chorus/0.5" },
    
    // Reed
    { "id": 64, "name": "Soprano Sax", "category": "Reed", "syntax": "/sound/square/lpf/2500/attack/0.05/sustain/0.8" },
    { "id": 65, "name": "Alto Sax", "category": "Reed", "syntax": "/sound/square/lpf/2000/attack/0.06/sustain/0.8" },
    { "id": 66, "name": "Tenor Sax", "category": "Reed", "syntax": "/sound/square/lpf/1500/attack/0.07/sustain/0.8" },
    { "id": 67, "name": "Baritone Sax", "category": "Reed", "syntax": "/sound/square/lpf/1000/attack/0.08/sustain/0.8" },
    { "id": 68, "name": "Oboe", "category": "Reed", "syntax": "/sound/triangle/lpf/1000/attack/0.1/sustain/0.8/vibrato/0.3" },
    { "id": 69, "name": "English Horn", "category": "Reed", "syntax": "/sound/triangle/lpf/900/attack/0.1/sustain/0.8/vibrato/0.2" },
    { "id": 70, "name": "Bassoon", "category": "Reed", "syntax": "/sound/triangle/lpf/600/attack/0.12/sustain/0.8" },
    { "id": 71, "name": "Clarinet", "category": "Reed", "syntax": "/sound/square/lpf/1200/attack/0.08/sustain/0.8" },
    
    // Pipe
    { "id": 72, "name": "Piccolo", "category": "Pipe", "syntax": "/sound/sine/lpf/4000/attack/0.05/sustain/0.9" },
    { "id": 73, "name": "Flute", "category": "Pipe", "syntax": "/sound/tri/lpf/2000/attack/0.1/sustain/0.9/vibrato/0.4" },
    { "id": 74, "name": "Recorder", "category": "Pipe", "syntax": "/sound/tri/lpf/1500/attack/0.05/sustain/0.9" },
    { "id": 75, "name": "Pan Flute", "category": "Pipe", "syntax": "/sound/tri/lpf/1000/attack/0.15/sustain/0.8" },
    { "id": 76, "name": "Blown Bottle", "category": "Pipe", "syntax": "/sound/sine/lpf/800/attack/0.1/sustain/1.0" },
    { "id": 77, "name": "Shakuhachi", "category": "Pipe", "syntax": "/sound/sine/lpf/800/attack/0.15/sustain/0.9/vibrato/0.3" },
    { "id": 78, "name": "Whistle", "category": "Pipe", "syntax": "/sound/sine/lpf/3000/attack/0.02/sustain/0.9" },
    { "id": 79, "name": "Ocarina", "category": "Pipe", "syntax": "/sound/tri/lpf/1200/attack/0.1/sustain/0.9/reverb/0.3" },
    
    // Synth Lead
    { "id": 80, "name": "Lead 1 (square)", "category": "Synth Lead", "syntax": "/sound/square/attack/0.01/sustain/0.8/release/0.1" },
    { "id": 81, "name": "Lead 2 (sawtooth)", "category": "Synth Lead", "syntax": "/sound/saw/attack/0.01/sustain/0.8/release/0.2" },
    { "id": 82, "name": "Lead 3 (calliope)", "category": "Synth Lead", "syntax": "/sound/saw/attack/0.01/sustain/0.8/release/0.1/lpf/2000/chorus/0.5" },
    { "id": 83, "name": "Lead 4 (chiff)", "category": "Synth Lead", "syntax": "/sound/tri/attack/0.05/sustain/0.8/release/0.2/lpf/3000" },
    { "id": 84, "name": "Lead 5 (charang)", "category": "Synth Lead", "syntax": "/sound/saw/attack/0.01/sustain/0.8/release/0.2/distort/0.5" },
    { "id": 85, "name": "Lead 6 (voice)", "category": "Synth Lead", "syntax": "/sound/saw/attack/0.2/sustain/1.0/release/0.5/chorus/0.5" },
    { "id": 86, "name": "Lead 7 (fifths)", "category": "Synth Lead", "syntax": "/sound/saw/attack/0.01/sustain/0.8/release/0.2/detune/700" },
    { "id": 87, "name": "Lead 8 (bass + lead)", "category": "Synth Lead", "syntax": "/sound/saw/attack/0.01/sustain/0.8/release/0.2/lpf/1000/lpq/0.5" },
    
    // Synth Pad
    { "id": 88, "name": "Pad 1 (new age)", "category": "Synth Pad", "syntax": "/sound/saw/attack/0.5/sustain/0.9/release/1.0/lpf/2000" },
    { "id": 89, "name": "Pad 2 (warm)", "category": "Synth Pad", "syntax": "/sound/saw/attack/0.8/sustain/0.9/release/1.5/lpf/1000" },
    { "id": 90, "name": "Pad 3 (polysynth)", "category": "Synth Pad", "syntax": "/sound/saw/attack/0.5/sustain/0.9/release/1.0/lpf/3000/chorus/0.4" },
    { "id": 91, "name": "Pad 4 (choir)", "category": "Synth Pad", "syntax": "/sound/tri/attack/1.0/sustain/0.8/release/1.5/chorus/0.8" },
    { "id": 92, "name": "Pad 5 (bowed)", "category": "Synth Pad", "syntax": "/sound/tri/attack/1.0/sustain/0.8/release/1.5/lpf/1500" },
    { "id": 93, "name": "Pad 6 (metallic)", "category": "Synth Pad", "syntax": "/sound/fm2/harmonics/2.0/timbre/0.5/attack/0.5/sustain/0.7" },
    { "id": 94, "name": "Pad 7 (halo)", "category": "Synth Pad", "syntax": "/sound/saw/attack/1.0/sustain/0.9/release/2.0/lpf/800/chorus/0.6/reverb/0.5" },
    { "id": 95, "name": "Pad 8 (sweep)", "category": "Synth Pad", "syntax": "/sound/saw/attack/1.0/sustain/0.9/release/2.0/lpf/1200/lpe/500" },
    
    // Synth Effects
    { "id": 96, "name": "FX 1 (rain)", "category": "Synth Effects", "syntax": "/sound/pnoise/timbre/0.5/morph/0.8/attack/0.1/release/2.0" },
    { "id": 97, "name": "FX 2 (soundtrack)", "category": "Synth Effects", "syntax": "/sound/saw/attack/0.5/sustain/0.9/release/2.0/lpf/2000" },
    { "id": 98, "name": "FX 3 (crystal)", "category": "Synth Effects", "syntax": "/sound/fm2/harmonics/3.0/timbre/0.8/attack/0.1/release/1.0" },
    { "id": 99, "name": "FX 4 (atmosphere)", "category": "Synth Effects", "syntax": "/sound/tri/attack/1.0/sustain/0.9/release/2.0/lpf/800" },
    { "id": 100, "name": "FX 5 (brightness)", "category": "Synth Effects", "syntax": "/sound/saw/attack/0.2/sustain/0.8/release/1.0/lpf/4000" },
    { "id": 101, "name": "FX 6 (goblins)", "category": "Synth Effects", "syntax": "/sound/pnoise/timbre/0.7/morph/0.5/attack/0.5/release/1.5" },
    { "id": 102, "name": "FX 7 (echoes)", "category": "Synth Effects", "syntax": "/sound/saw/attack/0.1/sustain/0.8/release/1.0/delay/0.5" },
    { "id": 103, "name": "FX 8 (sci-fi)", "category": "Synth Effects", "syntax": "/sound/fm2/harmonics/4.0/timbre/0.9/attack/0.1/release/1.0" },
    
    // Ethnic
    { "id": 104, "name": "Sitar", "category": "Ethnic", "syntax": "/sound/string/timbre/0.8/morph/0.2/decay/1.0" },
    { "id": 105, "name": "Banjo", "category": "Ethnic", "syntax": "/sound/string/timbre/0.6/morph/0.4/decay/0.5" },
    { "id": 106, "name": "Shamisen", "category": "Ethnic", "syntax": "/sound/string/timbre/0.7/morph/0.3/decay/0.6" },
    { "id": 107, "name": "Koto", "category": "Ethnic", "syntax": "/sound/string/timbre/0.8/morph/0.1/decay/1.5" },
    { "id": 108, "name": "Kalimba", "category": "Ethnic", "syntax": "/sound/modal/harmonics/0.4/timbre/0.6/decay/0.8" },
    { "id": 109, "name": "Bag pipe", "category": "Ethnic", "syntax": "/sound/saw/attack/0.1/sustain/1.0/lpf/2000" },
    { "id": 110, "name": "Fiddle", "category": "Ethnic", "syntax": "/sound/saw/attack/0.1/sustain/1.0/lpf/3000" },
    { "id": 111, "name": "Shanai", "category": "Ethnic", "syntax": "/sound/saw/attack/0.1/sustain/1.0/lpf/2500" },
    
    // Percussive
    { "id": 112, "name": "Tinkle Bell", "category": "Percussive", "syntax": "/sound/modal/harmonics/0.9/timbre/0.9/decay/0.5/sustain/0" },
    { "id": 113, "name": "Agogo", "category": "Percussive", "syntax": "/sound/modal/harmonics/0.8/timbre/0.8/decay/0.3/sustain/0" },
    { "id": 114, "name": "Steel Drums", "category": "Percussive", "syntax": "/sound/modal/harmonics/0.2/timbre/0.8/decay/1.0/sustain/0" },
    { "id": 115, "name": "Woodblock", "category": "Percussive", "syntax": "/sound/modal/harmonics/0.5/timbre/0.5/decay/0.1/sustain/0" },
    { "id": 116, "name": "Taiko Drum", "category": "Percussive", "syntax": "/sound/modal/harmonics/0.1/timbre/0.4/decay/0.5/sustain/0" },
    { "id": 117, "name": "Melodic Tom", "category": "Percussive", "syntax": "/sound/modal/harmonics/0.3/timbre/0.6/decay/0.4/sustain/0" },
    { "id": 118, "name": "Synth Drum", "category": "Percussive", "syntax": "/sound/pnoise/timbre/0.8/morph/0.2/decay/0.3/sustain/0" },
    { "id": 119, "name": "Reverse Cymbal", "category": "Percussive", "syntax": "/sound/white/attack/0.01/decay/1.0/sustain/0" },
    
    // Sound Effects
    { "id": 120, "name": "Guitar Fret Noise", "category": "Sound Effects", "syntax": "/sound/pnoise/timbre/0.9/morph/0.9/attack/0.05/release/0.1" },
    { "id": 121, "name": "Breath Noise", "category": "Sound Effects", "syntax": "/sound/white/lpf/1000/attack/0.1/release/0.2" },
    { "id": 122, "name": "Seashore", "category": "Sound Effects", "syntax": "/sound/white/lpf/500/attack/1.0/release/2.0" },
    { "id": 123, "name": "Bird Tweet", "category": "Sound Effects", "syntax": "/sound/sine/freq/2000/fm/50/attack/0.01/release/0.1" },
    { "id": 124, "name": "Telephone Ring", "category": "Sound Effects", "syntax": "/sound/square/freq/800/am/20/attack/0.01/release/0.1" },
    { "id": 125, "name": "Helicopter", "category": "Sound Effects", "syntax": "/sound/white/lpf/500/am/10/attack/0.1/release/0.5" },
    { "id": 126, "name": "Applause", "category": "Sound Effects", "syntax": "/sound/white/lpf/2000/attack/0.1/release/1.0" },
    { "id": 127, "name": "Gunshot", "category": "Sound Effects", "syntax": "/sound/pnoise/timbre/0.1/morph/0.8/attack/0.01/release/0.5" }
  ]
};